name: Build and Package Tauri App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Tauri App for Windows
        run: npm run build-tauri -- --target=win
        
      - name: Build Tauri App for Linux
        run: npm run build-tauri -- --target=linux
        
      - name: Build Tauri App for macOS
        run: npm run build-tauri -- --target=mac
        
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app
          path: |
            ./src-tauri/target/release/bundle/app-win.exe
            ./src-tauri/target/release/bundle/app-linux
            ./src-tauri/target/release/bundle/app-macos.app
            
